# Generated by Django 4.2.15 on 2024-11-05 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0034_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='college',
        ),
    ]
