# Generated by Django 4.2.16 on 2024-11-15 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_new_user_is_deleted'),
        ('test_series', '0037_messages_recipient_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages1',
            name='recipient_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_received_messages', to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='messages1',
            name='recipient_college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_received_messages', to='login.universityincharge'),
        ),
        migrations.AddField(
            model_name='messages1',
            name='recipient_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_received_messages', to='login.new_user'),
        ),
    ]
