# Generated by Django 4.2.16 on 2024-11-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0039_exam_proctoringsession_question_userscore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment1',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='company',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='recipient_candidate',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='recipient_company',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='recipient_student',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='student',
        ),
        migrations.RemoveField(
            model_name='messages1',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='messages1',
            name='college',
        ),
        migrations.RemoveField(
            model_name='messages1',
            name='recipient_candidate',
        ),
        migrations.RemoveField(
            model_name='messages1',
            name='recipient_college',
        ),
        migrations.RemoveField(
            model_name='messages1',
            name='recipient_student',
        ),
        migrations.RemoveField(
            model_name='messages1',
            name='student',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Attachment1',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Messages1',
        ),
    ]
