# Generated by Django 4.2.16 on 2024-11-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0041_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='user',
        ),
    ]
