# Generated by Django 4.2.16 on 2024-11-19 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_new_user_is_deleted'),
        ('test_series', '0042_remove_exam_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
    ]
