# Generated by Django 4.2.16 on 2024-11-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0043_exam_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='user',
        ),
    ]
