# Generated by Django 4.2.15 on 2024-10-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0088_alter_application_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
