# Generated by Django 4.2.15 on 2024-10-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0090_message_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='college_recipient',
        ),
    ]
