# Generated by Django 4.2.15 on 2024-10-18 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0092_college_message_college_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college_attachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='job_portal.college_message'),
        ),
    ]
