# Generated by Django 4.2.15 on 2024-10-18 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0093_alter_college_attachment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='company_recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AlterField(
            model_name='college_message',
            name='college_recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clg_recipient', to='job_portal.college'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
