# Generated by Django 4.2.15 on 2024-10-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0095_message_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college_message',
            name='college_recipient',
        ),
        migrations.RemoveField(
            model_name='college_message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='College_Attachment',
        ),
        migrations.DeleteModel(
            name='College_Message',
        ),
    ]
