# Generated by Django 4.2.15 on 2024-10-23 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0098_remove_usersubscription_current_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='job',
            name='country',
        ),
        migrations.RemoveField(
            model_name='job',
            name='expiration_code',
        ),
        migrations.RemoveField(
            model_name='job',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='job',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='job',
            name='promoting_job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='security_code',
        ),
        migrations.RemoveField(
            model_name='job1',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='job1',
            name='country',
        ),
        migrations.RemoveField(
            model_name='job1',
            name='expiration_code',
        ),
        migrations.RemoveField(
            model_name='job1',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='job1',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='job1',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='job1',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='job1',
            name='promoting_job',
        ),
        migrations.RemoveField(
            model_name='job1',
            name='security_code',
        ),
    ]
