# Generated by Django 4.2.15 on 2024-10-23 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_companyincharge_token_alter_consultant_token_and_more'),
        ('job_portal', '0100_company_company_in_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='university_in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.AddField(
            model_name='student',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
    ]
