# Generated by Django 4.2.15 on 2024-10-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_companyincharge_token_alter_consultant_token_and_more'),
        ('job_portal', '0102_education1_achievements_job_seeker_achievements_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education1',
            new_name='Education2',
        ),
    ]
