# Generated by Django 4.2.15 on 2024-10-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_rename_education_new_user_educations'),
        ('job_portal', '0103_rename_education1_education2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education2',
            new_name='Education',
        ),
    ]
