# Generated by Django 4.2.15 on 2024-10-23 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_rename_education_new_user_educations'),
        ('job_portal', '0104_rename_education2_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AlterField(
            model_name='application',
            name='company_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge'),
        ),
        migrations.AlterField(
            model_name='application1',
            name='university_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='company_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AlterField(
            model_name='candidatestatus_not_eligible',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AlterField(
            model_name='candidatestatus_not_eligible',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AlterField(
            model_name='candidatestatus_rejected',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AlterField(
            model_name='candidatestatus_rejected',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AlterField(
            model_name='candidatestatus_selected',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AlterField(
            model_name='candidatestatus_selected',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AlterField(
            model_name='candidatestatus_under_review',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AlterField(
            model_name='candidatestatus_under_review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AlterField(
            model_name='college',
            name='university_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.AlterField(
            model_name='college_attachment',
            name='university_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.AlterField(
            model_name='college_message',
            name='university_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.AlterField(
            model_name='collegeenquiry',
            name='university_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge'),
        ),
        migrations.AlterField(
            model_name='education',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to='job_portal.resume'),
        ),
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_entries', to='job_portal.resume'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge'),
        ),
        migrations.AlterField(
            model_name='job1',
            name='university_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.AlterField(
            model_name='message',
            name='company_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge'),
        ),
        migrations.AlterField(
            model_name='message',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AlterField(
            model_name='screeninganswer',
            name='company_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge'),
        ),
        migrations.AlterField(
            model_name='screeninganswer',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AlterField(
            model_name='screeninganswer',
            name='university_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.AlterField(
            model_name='screeninganswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AlterField(
            model_name='screeningquestion',
            name='company_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge'),
        ),
        migrations.AlterField(
            model_name='screeningquestion',
            name='university_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.AlterField(
            model_name='student',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AlterField(
            model_name='studentenquiry',
            name='university_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='university_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
    ]
