# Generated by Django 4.2.15 on 2024-10-24 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_rename_education_new_user_educations'),
        ('job_portal', '0105_alter_achievements_job_seeker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='education',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='project',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_seeker',
        ),
        migrations.CreateModel(
            name='JobSeeker_Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=100)),
                ('last_name', models.CharField(default='John Doe', max_length=100)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('phone', models.CharField(default='000-000-0000', max_length=20)),
                ('address', models.TextField(default='N/A')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('website_urls', models.JSONField(default=list)),
                ('skills', models.TextField(default='Not specified')),
                ('activities', models.TextField(default='None')),
                ('interests', models.TextField(default='None')),
                ('languages', models.TextField(default='None')),
                ('bio', models.TextField(default='None')),
                ('city', models.CharField(default='Mumbai', max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('zipcode', models.CharField(default='522426', max_length=6)),
                ('Attachment', models.FileField(default='Unknown', upload_to='attachments/')),
                ('delete', models.BooleanField(default=False)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker_Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('contact_info', models.CharField(default='Not provided', max_length=100)),
                ('relationship', models.CharField(default='N/A', max_length=100)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='job_portal.jobseeker_resume')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker_Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unknown', max_length=100)),
                ('publisher', models.CharField(default='Unknown', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='job_portal.jobseeker_resume')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Project', max_length=100)),
                ('description', models.TextField(default='No description')),
                ('project_link', models.TextField(default=list)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='job_portal.jobseeker_resume')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker_Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Not specified')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='objective', to='job_portal.jobseeker_resume')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='Unknown', max_length=100)),
                ('company_name', models.CharField(default='Unknown', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(default='No description')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_entries', to='job_portal.jobseeker_resume')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker_Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_or_degree', models.CharField(default='Unknown', max_length=100)),
                ('school_or_university', models.CharField(default='Unknown', max_length=100)),
                ('grade_or_cgpa', models.CharField(default='N/A', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(default='No description')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to='job_portal.jobseeker_resume')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker_Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='job_portal.jobseeker_resume')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker_Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unknown', max_length=100)),
                ('publisher', models.CharField(default='Unknown', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='job_portal.jobseeker_resume')),
            ],
        ),
    ]
