# Generated by Django 4.2.15 on 2024-10-24 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_rename_education_new_user_educations'),
        ('job_portal', '0106_remove_achievements_job_seeker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatestatus_not_eligible',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='candidatestatus_rejected',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='candidatestatus_selected',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='candidatestatus_under_review',
            name='job_seeker',
        ),
        migrations.CreateModel(
            name='JobSeekerStatus_under_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=255)),
                ('last_name', models.CharField(default='Doe', max_length=255)),
                ('status', models.CharField(default='under_review', max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('job_id', models.IntegerField()),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerStatus_selected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=255)),
                ('last_name', models.CharField(default='Doe', max_length=255)),
                ('status', models.CharField(default='selected', max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('job_id', models.IntegerField()),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerStatus_rejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=255)),
                ('last_name', models.CharField(default='Doe', max_length=255)),
                ('status', models.CharField(default='rejected', max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('job_id', models.IntegerField()),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerStatus_not_eligible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=255)),
                ('last_name', models.CharField(default='Doe', max_length=255)),
                ('status', models.CharField(default='not_eligible', max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('job_id', models.IntegerField()),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker')),
            ],
        ),
    ]
