# Generated by Django 4.2.15 on 2024-10-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0108_remove_student_job_seeker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatestatus_selected',
            name='user',
        ),
    ]
