# Generated by Django 4.2.15 on 2024-10-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0109_remove_candidatestatus_selected_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerstatus_rejected',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='jobseekerstatus_selected',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='jobseekerstatus_under_review',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='candidatestatus_not_eligible',
            name='user',
        ),
        migrations.RemoveField(
            model_name='candidatestatus_rejected',
            name='user',
        ),
        migrations.RemoveField(
            model_name='candidatestatus_under_review',
            name='user',
        ),
        migrations.DeleteModel(
            name='JobSeekerStatus_not_eligible',
        ),
        migrations.DeleteModel(
            name='JobSeekerStatus_rejected',
        ),
        migrations.DeleteModel(
            name='JobSeekerStatus_selected',
        ),
        migrations.DeleteModel(
            name='JobSeekerStatus_under_review',
        ),
    ]
