# Generated by Django 4.2.15 on 2024-10-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0111_remove_application_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate1Status_not_eligible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=255)),
                ('last_name', models.CharField(default='Doe', max_length=255)),
                ('status', models.CharField(default='not_eligible', max_length=20)),
                ('college_id', models.IntegerField()),
                ('job_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate1Status_rejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=255)),
                ('last_name', models.CharField(default='Doe', max_length=255)),
                ('status', models.CharField(default='rejected', max_length=20)),
                ('college_id', models.IntegerField()),
                ('job_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate1Status_selected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=255)),
                ('last_name', models.CharField(default='Doe', max_length=255)),
                ('status', models.CharField(default='selected', max_length=20)),
                ('college_id', models.IntegerField()),
                ('job_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate1Status_under_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=255)),
                ('last_name', models.CharField(default='Doe', max_length=255)),
                ('status', models.CharField(default='under_review', max_length=20)),
                ('college_id', models.IntegerField()),
                ('job_id', models.IntegerField()),
            ],
        ),
    ]
