# Generated by Django 4.2.15 on 2024-10-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0113_rename_job_seeker_message_sender1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender1',
            new_name='sender_job_seeker',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='sender_new_user',
        ),
    ]
