# Generated by Django 4.2.15 on 2024-10-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0114_rename_sender1_message_sender_job_seeker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='company_in_charge',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='company_in_charge',
        ),
    ]
