# Generated by Django 4.2.15 on 2024-10-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_remove_companyincharge_user_remove_consultant_user_and_more'),
        ('job_portal', '0115_remove_attachment_company_in_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_job_seeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_new_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='login.new_user'),
        ),
    ]
