# Generated by Django 4.2.15 on 2024-10-25 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_remove_companyincharge_user_remove_consultant_user_and_more'),
        ('job_portal', '0116_alter_message_sender_job_seeker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college_message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='college_message',
            name='university_in_charge',
        ),
        migrations.AddField(
            model_name='college_message',
            name='sender_jobseeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='college_message',
            name='sender_newuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_new_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
    ]
