# Generated by Django 4.2.15 on 2024-10-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0117_remove_college_message_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college_attachment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='college_attachment',
            name='university_in_charge',
        ),
        migrations.RemoveField(
            model_name='college_message',
            name='college_recipient',
        ),
        migrations.RemoveField(
            model_name='college_message',
            name='sender_jobseeker',
        ),
        migrations.RemoveField(
            model_name='college_message',
            name='sender_newuser',
        ),
        migrations.RemoveField(
            model_name='message',
            name='company_recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_job_seeker',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_new_user',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='College_Attachment',
        ),
        migrations.DeleteModel(
            name='College_Message',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
