# Generated by Django 4.2.15 on 2024-10-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0120_alter_message_sender_job_seeker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college_attachment',
            name='university_in_charge',
        ),
    ]
