# Generated by Django 4.2.15 on 2024-10-25 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_new_user_is_deleted'),
        ('job_portal', '0121_remove_college_attachment_university_in_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeScreeningAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_answers', to='job_portal.application1')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeScreeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_questions', to='job_portal.job1')),
                ('university_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyScreeningAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_answers', to='job_portal.application')),
                ('company_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyScreeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('company_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_questions', to='job_portal.job')),
            ],
        ),
        migrations.RemoveField(
            model_name='screeningquestion',
            name='company_in_charge',
        ),
        migrations.RemoveField(
            model_name='screeningquestion',
            name='job',
        ),
        migrations.RemoveField(
            model_name='screeningquestion',
            name='university_in_charge',
        ),
        migrations.DeleteModel(
            name='ScreeningAnswer',
        ),
        migrations.DeleteModel(
            name='ScreeningQuestion',
        ),
        migrations.AddField(
            model_name='companyscreeninganswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='job_portal.companyscreeningquestion'),
        ),
        migrations.AddField(
            model_name='collegescreeninganswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='job_portal.collegescreeningquestion'),
        ),
        migrations.AddField(
            model_name='collegescreeninganswer',
            name='university_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
    ]
