# Generated by Django 4.2.15 on 2024-10-25 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_new_user_is_deleted'),
        ('job_portal', '0123_remove_interview_student_alter_interview_job_seeker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='company_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.companyincharge'),
        ),
    ]
