# Generated by Django 4.2.15 on 2024-10-25 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_new_user_is_deleted'),
        ('job_portal', '0125_application_job_seeker_application_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application1',
            name='job_seeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.jobseeker'),
        ),
        migrations.AddField(
            model_name='application1',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
    ]
