# Generated by Django 4.2.15 on 2024-10-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0130_interview_applicants_interview_jobs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='applicants',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='university_in_charge',
        ),
    ]
