# Generated by Django 4.2.15 on 2024-10-26 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_new_user_is_deleted'),
        ('job_portal', '0132_alter_collegeenquiry_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeenquiry',
            name='new_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
        migrations.AlterField(
            model_name='collegeenquiry',
            name='status',
            field=models.CharField(choices=[('replied', 'Replied'), ('not-replied', 'Not-Replied')], default='not-replied', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentenquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
