# Generated by Django 4.2.15 on 2024-10-27 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0134_remove_collegeenquiry_university_in_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender_job_seeker',
            new_name='receiptent_job_seeker_job_seeker',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_new_user',
            new_name='receiptent_new_user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='company_recipient',
            new_name='sender_company',
        ),
    ]
