# Generated by Django 4.2.15 on 2024-10-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0136_rename_receiptent_job_seeker_job_seeker_message_receiptent_job_seeker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender_company',
        ),
    ]
