# Generated by Django 4.2.15 on 2024-10-27 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_new_user_is_deleted'),
        ('job_portal', '0137_remove_message_sender_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college_message',
            name='college_recipient',
        ),
        migrations.AddField(
            model_name='college_message',
            name='university_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.AlterField(
            model_name='college_message',
            name='sender_newuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
    ]
