# Generated by Django 4.2.15 on 2024-10-27 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0138_remove_college_message_college_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college_message',
            name='college_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clg_recipient', to='job_portal.college'),
        ),
    ]
