# Generated by Django 4.2.15 on 2024-10-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0140_remove_college_message_college_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college_message',
            old_name='sender_jobseeker',
            new_name='receiptent_job_seeker',
        ),
        migrations.RenameField(
            model_name='college_message',
            old_name='sender_newuser',
            new_name='receiptent_new_user',
        ),
    ]
