# Generated by Django 4.2.15 on 2024-10-27 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_new_user_is_deleted'),
        ('job_portal', '0141_rename_sender_jobseeker_college_message_receiptent_job_seeker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college_message',
            name='receiptent_new_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.new_user'),
        ),
    ]
