# Generated by Django 4.2.15 on 2024-10-28 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0144_job_unique_job_id_alter_job_table_alter_job1_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='unique_job_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
