# Generated by Django 4.2.15 on 2024-10-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0148_alter_job_unique_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='unique_job_id',
            field=models.UUIDField(default=11513102121411914771966266774817994033, editable=False, unique=True),
        ),
    ]
