# Generated by Django 4.2.15 on 2024-10-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0151_alter_job_unique_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='unique_job_id',
            field=models.UUIDField(default=43548736930726579137391472315710436657, editable=False, unique=True),
        ),
    ]
