# Generated by Django 4.2.15 on 2024-10-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0154_job_unique_job_id_as_int_alter_job_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='unique_job_id_as_int',
            field=models.IntegerField(editable=False, null=True, unique=True),
        ),
    ]
