# Generated by Django 4.2.15 on 2024-10-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0156_alter_job_unique_job_id_as_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
