# Generated by Django 4.2.15 on 2024-11-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0157_alter_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application1',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application1',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application1',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
