# Generated by Django 4.2.15 on 2024-11-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0159_studentenquiry_created_at_visitor_visited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application1',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
