# Generated by Django 4.2.15 on 2024-11-07 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0160_alter_application1_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeenquiry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
