# Generated by Django 4.2.16 on 2024-11-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0161_collegeenquiry_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college_attachment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='college_message',
            name='receiptent_job_seeker',
        ),
        migrations.RemoveField(
            model_name='college_message',
            name='receiptent_new_user',
        ),
        migrations.RemoveField(
            model_name='college_message',
            name='university_in_charge',
        ),
        migrations.RemoveField(
            model_name='message',
            name='company_in_charge',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiptent_job_seeker',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiptent_new_user',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='College_Attachment',
        ),
        migrations.DeleteModel(
            name='College_Message',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
