# Generated by Django 4.2.15 on 2024-10-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_jobseeker_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
