# Generated by Django 4.2.15 on 2024-10-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_jobseeker_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyincharge',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='new_user',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='universityincharge',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
