# Generated by Django 4.2.15 on 2024-10-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_companyincharge_token_alter_consultant_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_user',
            old_name='education',
            new_name='educations',
        ),
    ]
