# Generated by Django 4.2.15 on 2024-10-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_rename_education_new_user_educations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyincharge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='universityincharge',
            name='user',
        ),
    ]
